modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "appmekadjust"
version = "${version}"
displayName = "AppMekAdjust"
authors = "yuko1101"
description = '''
Rebalances Mekanism mod.
'''
#logoFile = ""

[[dependencies.appmekadjust]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.appmekadjust]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.appmekadjust]]


[[mixins]]
config = "appmekadjust.mixins.json"
