modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "appmekadjust"
version = "${version}"
displayName = "AppMekAdjust"
authors = "yuko1101"
description = '''
Rebalances Mekanism mod.
'''
#logoFile = ""

[[dependencies.appmekadjust]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.appmekadjust]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.appmekadjust]]
modId = "ae2"
type = "required"
versionRange = "[${ae2_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.appmekadjust]]
modId = "mekanism"
type = "required"
versionRange = "[${mekanism_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.appmekadjust]]
modId = "appmek"
type = "required"
versionRange = "[${appmek_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "appmekadjust.mixins.json"

[[mixins]]
config = "neoforge.appmekadjust.mixins.json"
